language: node_js
sudo: false
node_js:
  - '6'

cache:
  directories:
    - node_modules
    - bower_components
    - docs/bower_components


# branches:
#   only:
#     - master
#
# before_script:
#   - npm install -g firebase-tools
#   - npm install -g @angular/cli
